# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Daily Story
email: filip@fis.name
description: > # this means to ignore newlines until "baseurl:"
  Daily comic strip based on the words from the Sketch a Day challenge
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://cz-fish.github.io/daily-story" # the base hostname & protocol for your site
baseurl: "/daily-story" # the subpath of your site, e.g. /blog
url: "https://cz-fish.github.io" # the base hostname & protocol for your site
github_username:  cz-fish

# Build settings
markdown: kramdown
